'''
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
'''


def compute():
    a = 1
    b = 2
    result = 2
    maxim = 4000000
    for n in range(3, maxim):
        if n == a + b:
            if n % 2 == 0:
                result += n
            a = b
            b = n

    return result


if __name__ == '__main__':
    print(compute())
